name: "Unit Test"

on:
  push:
    branches: [main]
  pull_request:
    branches: ["*"]
  merge_group:

jobs:
  go-test:
    strategy:
      matrix:
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    permissions:
      contents: read

    steps:
    - name: Checkout code
      uses: actions/checkout@44c2b7a8a4ea60a981eaca3cf939b5f4305c123b # v4.1.5
    - name: Install Go
      uses: actions/setup-go@0c52d547c9bc32b1aa3301fd7a9cb496313a4491 # v5.0.0
      with:
        go-version-file: go.mod
    - name: Go Test
      run: |
        make govet
        make gotest
