name: "Unit Test"

on:
  push:
    branches: [main]
  pull_request:
    branches: ["*"]
  merge_group:

jobs:
  go-test:
    strategy:
      matrix:
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    permissions:
      contents: read

    steps:
    - name: Checkout code
      uses: actions/checkout@9bb56186c3b09b4f86b1c65136769dd318469633 # v4.1.2
    - name: Install Go
      uses: actions/setup-go@6edd4406fa81c3da01a34fa6f6343087c207a568 # v3.5.0
      with:
        go-version-file: go.mod
    - name: Go Test
      run: |
        make govet
        make gotest
